# Generated by Django 5.0
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_parent', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='AppPrivacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package_name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('app_name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('permissions', models.JSONField(default=list)),
                ('baseline_privacy_score', models.PositiveIntegerField(default=80)),
            ],
            options={
                'verbose_name': 'app privacy profile',
                'verbose_name_plural': 'app privacy profiles',
                'ordering': ['app_name'],
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('avatar_color', models.CharField(blank=True, default='#6366F1', help_text='Hex color code for avatar', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='Parent user who owns this child profile', on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'child profile',
                'verbose_name_plural': 'child profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(blank=True, default='', max_length=17)),
                ('device_type', models.CharField(choices=[('PHONE', 'Phone'), ('LAPTOP', 'Laptop'), ('TABLET', 'Tablet'), ('TV', 'TV'), ('CONSOLE', 'Console'), ('ROUTER', 'Router'), ('IOT', 'IoT Device'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('is_trusted', models.BooleanField(default=False)),
                ('is_blocked', models.BooleanField(default=False)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'network device',
                'verbose_name_plural': 'network devices',
                'ordering': ['-last_seen_at'],
                'unique_together': {('owner', 'mac_address')},
            },
        ),
        migrations.CreateModel(
            name='NetworkScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('network_ssid', models.CharField(blank=True, max_length=255, null=True)),
                ('network_bssid', models.CharField(blank=True, max_length=17, null=True)),
                ('json_payload', models.JSONField(default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'network scan log',
                'verbose_name_plural': 'network scan logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('BLOCK_APP', 'Block App'), ('LIMIT_USAGE', 'Limit Usage'), ('BEDTIME', 'Bedtime')], max_length=20)),
                ('app_package_name', models.CharField(blank=True, help_text='Package name for BLOCK_APP rule', max_length=255, null=True)),
                ('category', models.CharField(blank=True, help_text='App category for LIMIT_USAGE rule', max_length=100, null=True)),
                ('daily_limit_minutes', models.PositiveIntegerField(blank=True, help_text='Daily usage limit in minutes', null=True)),
                ('bedtime_start', models.TimeField(blank=True, help_text='Start of bedtime restriction', null=True)),
                ('bedtime_end', models.TimeField(blank=True, help_text='End of bedtime restriction', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='core.childprofile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parental_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'parental rule',
                'verbose_name_plural': 'parental rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrivacyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_package_name', models.CharField(max_length=255)),
                ('app_name', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=list)),
                ('network_usage_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='MEDIUM', max_length=10)),
                ('calculated_privacy_score', models.PositiveIntegerField()),
                ('explanation', models.TextField()),
                ('suggested_action', models.CharField(choices=[('KEEP', 'Keep'), ('REVIEW', 'Review Permissions'), ('CONSIDER_UNINSTALL', 'Consider Uninstalling')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'privacy check',
                'verbose_name_plural': 'privacy checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RuleViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.childprofile')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='core.parentalrule')),
            ],
            options={
                'verbose_name': 'rule violation',
                'verbose_name_plural': 'rule violations',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('GOOGLE', 'Google'), ('APPLE', 'Apple')], max_length=20)),
                ('provider_user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'social account',
                'verbose_name_plural': 'social accounts',
                'unique_together': {('provider', 'provider_user_id')},
            },
        ),
    ]
